### ISSUE TITLE
Accounts don't match walk wallet when using the same private key or seed

### ISSUE THREAD

**Issue by faddat** [walkbean/vsys-sdk-go#4]
All of this concerns:
https://github.com/faddat/cryptostoragewidget

For this trial, I've been using mainnnet addresses that I control.  First, I tried acc.BuildFromPrivateKey, with the private key copied/pasted from walk wallet hot.  When I acc.getinfo, I get a different address than the one in walk wallet, and the transaction of course fails because there's no funds in that account.  

Later, I tried acc.BuildFromSeed using my seed from walk wallet hot, and a nonce of zero, but I got the same result.  

I guess that I could send to one of these new addresses that are being generated, but I prefer to understand what I'm doing wrong here so that I can begin making very interesting Attachments to the VSYS blockchain.  

Thanks for any help you can offer

**Comment by faddat** [comment]
1) I was successful in making transactions:

TXID's:
65rrP2u2qUct97yuA9wGb5RiiK55Ywi8cCGVrXvcYd7Z
7nSCNszLVgUhr4cdV4ipM4wgjZzxrJqRZ9afwuaaNgjA
AYzmPdCBtfoHhC6UYZ5QUF8pGpZboehybCkv367f935G
HghE9HVPdL2coCXuaHdqhgM9LCVDTkejXsSMR3sjUt4s
23m7gE29dyRtvR1RDj8WsVYhMTzpzRCzN2MMNLLUGcgF
CqUZaUJV4gJw2hNndfX7zZHK9nFjuUVE6zWyiuv6aBgz

However.... I'm not too sure where the address is coming from, since it is different from the one in walk wallet hot with the same seed.  Anyhow once I funded the address, it worked great.  

Thanks!

**Comment by faddat** [comment]
For debug purposes, I've made an empty mainnet walk wallet address and private key.  Here are the results:

```
Walk wallet address:  AR6QxUtW1xH9Rkok8zKJG4f2GPoiWTjVpgu
Walk wallet private key: 3C96LqMhnUkPL7xdmRVrX8vKt8Fr53iM7yq9iijj7xJW
```

But my SDK program says:
```
Your Private Key is:  3C96LqMhnUkPL7xdmRVrX8vKt8Fr53iM7yq9iijj7xJW
Your address is:  ARJTBBrX2jbhFXYqfATbnRMdyBFFFXFMmFp
```

**Comment by walkbean** [comment]
Hi faddat, I can't reproduce the address problem. Under the main network, I tested the private key you provided and find that the address of the SDK is the same as the Walk Wallet. Maybe I need more information to check out what happened there, please let me know if the latest version of the SDK still has this problem. Thank you.

**Comment by faddat** [comment]
I tend to think you're right about this one-- probably it's a problem with how I'm reading the file `privatekey` in my code.  I'll keep chasing it down, and I'm closing this issue for now.  

Thanks for your help!

PS: By putting the private key directly in my code, I was able to eventually get the same address as the walk wallet.  So, I'm assuming it's an issue on my end.
