### ISSUE TITLE
"Invalid Attachment" when passing []byte as attachment

### ISSUE THREAD

**Issue by faddat** [walkbean/vsys-sdk-go#6]
2) When I try to set an attachment like this:

https://github.com/faddat/cryptostoragewidget/blob/587f23e9d6e9526a1f8d8892022ab476e9f0801e/main.go#L41

(and by replacing the attachment in line 42), it tells me that I've got an invalid attachment.

**Comment by walkbean** [comment]
Hi faddat, this is a bug and thanks for your information. I made some changes to the api. The problem has been fixed and please let me know if the latest SDK works. Thank you.
